name: TimeGuard
main: com.kraken.timeguard.TimeGuard
version: 2.0
commands: 
     timeguard:
        description: Set a timeguard.
        usage: /<command>
     goto:
        description: Teleport to a specific world.
        usage: /<command>
     played:
        description: Teleport to a specific world.
        usage: /<command>
     version:
        description: Get the current version of this plugin.
        usage: /<command>